export enum UserRole {
  CUSTOMER = "CUSTOMER",
  STORE_MANAGER = "STORE_MANAGER",
  ADMIN = "ADMIN",
}

export enum OrderStatus {
  PLACED = "PLACED",
  ACCEPTED = "ACCEPTED",
  PICKING = "PICKING",
  PACKED = "PACKED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
}

export enum ProductCategory {
  GROCERY = "GROCERY",
  GENERAL_MERCHANDISE = "GENERAL_MERCHANDISE",
  ELECTRONICS = "ELECTRONICS",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}
